[package]
name = "svg_experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.10.0"
ggez = "0.7"
glam = "0.20.2"
rand = "0.8.5"
quick-xml = "0.23.0"